### ISSUE TITLE
Error on opening documents

### ISSUE THREAD

**Issue by oschihin** [keeps/dbptk-desktop#42]
Hi
I have a SIARD-file with blobs included (mainly pdf, some docx). When on a document entry, I click on "Download" and get the following error message:

```xml
<apiResponseMessage>
    <message>RESTException: Remote exception caused by GenericException: Zip archive entry is missing</message>
    <type>error</type>
</apiResponseMessage>
```

Can someone give me a clue? Is there something wrong with the file, or might this be an application error?
Thanks

**Comment by luis100** [comment]
Could you provide the log file, available on the menu Help -> Logs -> DBPTK Logs (dbvtk.log file)
Before uploading, inspect the log file to ensure there is no sensitive information.

**Comment by oschihin** [comment]
Been away, so finally here is the log file. There are many error message, only two instances are copied here. Is this an application problem or a siard error? Thanks for having a look at it.

```log
2022-03-14 12:28:07,237 [main] INFO  c.d.c.server.ViewerConfiguration - Copying files from classpath prefix=config/, destination=C:\Users\ssvasco\.dbvtk\example-config, removePrefix=true, excludePaths=[config/i18n/client, config/i18n/I18N.gwt.xml]
2022-03-14 12:28:07,598 [main] INFO  c.d.c.server.ViewerConfiguration - DBVTK loading completed with success!
2022-03-14 12:28:09,770 [main] INFO  com.databasepreservation.DBVTK - Starting DBVTK v2.5.10 on PDNB0038022 with PID 8996 (C:\Users\ssvasco\AppData\Local\Programs\dbptk-desktop\resources\app.asar.unpacked\resources\war\dbvtk.war started by SSVASCO in C:\Users\ssvasco\AppData\Local\Programs\dbptk-desktop\resources\app.asar.unpacked)
2022-03-14 12:28:09,772 [main] INFO  com.databasepreservation.DBVTK - No active profile set, falling back to default profiles: default
2022-03-14 12:28:10,244 [background-preinit] WARN  o.s.h.c.j.Jackson2ObjectMapperBuilder - For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2022-03-14 12:28:32,048 [main] INFO  c.d.c.s.i.f.EmbeddedSolrClientFactory - Instantiating SOLR Embedded at C:\Users\ssvasco\.dbvtk\index
2022-03-14 12:28:33,817 [main] WARN  o.e.j.u.ssl.SslContextFactory.config - Trusting all certificates configured for Client@77192705[provider=null,keyStore=null,trustStore=null]
2022-03-14 12:28:33,818 [main] WARN  o.e.j.u.ssl.SslContextFactory.config - No Client EndPointIdentificationAlgorithm configured for Client@77192705[provider=null,keyStore=null,trustStore=null]
2022-03-14 12:28:33,835 [main] WARN  o.e.j.u.ssl.SslContextFactory.config - Trusting all certificates configured for Client@55795845[provider=null,keyStore=null,trustStore=null]
2022-03-14 12:28:33,836 [main] WARN  o.e.j.u.ssl.SslContextFactory.config - No Client EndPointIdentificationAlgorithm configured for Client@55795845[provider=null,keyStore=null,trustStore=null]
2022-03-14 12:28:33,860 [main] WARN  org.apache.solr.core.CoreContainer - Not all security plugins configured!  authentication=disabled authorization=disabled.  Solr is only as secure as you make it. Consider configuring authentication/authorization before exposing Solr to users internal or external.  See https://s.apache.org/solrsecurity for more info
2022-03-14 12:28:45,937 [main] INFO  c.d.c.s.i.schema.SolrBootstrapUtils - Bootstrapping schemas
2022-03-14 12:28:45,971 [main] INFO  c.d.c.s.i.schema.SolrBootstrapUtils - Collection dbv-databases is up to date
2022-03-14 12:28:45,978 [main] INFO  c.d.c.s.i.schema.SolrBootstrapUtils - Collection dbv-searches is up to date
2022-03-14 12:28:45,981 [main] INFO  c.d.c.s.i.schema.SolrBootstrapUtils - Collection dbv-activity-logs is up to date
2022-03-14 12:28:45,985 [main] INFO  c.d.c.s.i.schema.SolrBootstrapUtils - Collection dbv-batch-jobs is up to date
2022-03-14 12:28:45,998 [main] INFO  c.d.common.filter.OnOffFilter - CasSingleSignOutFilter is OFF
2022-03-14 12:28:45,999 [main] INFO  c.d.common.filter.OnOffFilter - CasApiAuthFilter is OFF
2022-03-14 12:28:46,000 [main] INFO  c.d.common.filter.OnOffFilter - CasValidationFilter is OFF
2022-03-14 12:28:46,000 [main] INFO  c.d.common.filter.OnOffFilter - CasRequestWrapperFilter is OFF
2022-03-14 12:28:46,005 [main] INFO  c.d.common.filter.OnOffFilter - InternalWebAuthFilter is OFF
2022-03-14 12:28:46,005 [main] INFO  c.d.common.filter.OnOffFilter - CasAuthenticationFilter is OFF
2022-03-14 12:28:47,248 [main] INFO  c.d.common.filter.OnOffFilter - CasWebAuthFilter is OFF
2022-03-14 12:28:47,249 [main] INFO  c.d.common.filter.OnOffFilter - InternalApiAuthFilter is OFF
2022-03-14 12:28:50,265 [main] INFO  com.databasepreservation.DBVTK - Started DBVTK in 42.422 seconds (JVM running for 47.215)
2022-03-14 12:33:47,635 [http-nio-auto-1-exec-4] INFO  c.d.c.s.controller.SIARDController - starting to import metadata database V:\Test-GAP\PROD_Daten-2016\PROD_2016.siard
2022-03-14 12:33:48,514 [http-nio-auto-1-exec-4] INFO  c.d.m.siard.update.SIARDEditModule - Importing SIARD version 2.1
2022-03-14 12:34:26,960 [http-nio-auto-1-exec-5] INFO  c.d.c.s.controller.SIARDController - Preparing the SIARD to be browsable (70373bf1-2fdb-4f1d-a2c5-82a5c7595d0f)
2022-03-14 12:34:26,961 [http-nio-auto-1-exec-5] INFO  c.d.c.s.controller.SIARDController - starting to convert database V:\Test-GAP\PROD_Daten-2016\PROD_2016.siard
2022-03-14 12:34:27,677 [http-nio-auto-1-exec-5] INFO  c.d.m.s.in.input.SIARDImportDefault - Importing SIARD version 2.1
2022-03-14 12:34:36,098 [http-nio-auto-1-exec-5] INFO  c.d.c.s.i.s.c.RowsCollection - Creating SOLR collection dbv-database-70373bf1-2fdb-4f1d-a2c5-82a5c7595d0f
2022-03-14 12:34:36,124 [http-nio-auto-1-exec-5] INFO  c.d.c.server.ViewerConfiguration - Copying files from classpath prefix=solr-config/, destination=C:\temp\dbptk\solr-config-4981047122394359851, removePrefix=true, excludePaths=[]
2022-03-14 12:34:36,189 [http-nio-auto-1-exec-5] INFO  c.d.c.s.i.f.EmbeddedSolrClientFactory - Creating SOLR collection dbv-database-70373bf1-2fdb-4f1d-a2c5-82a5c7595d0f
2022-03-14 12:34:37,843 [http-nio-auto-1-exec-5] INFO  c.d.c.s.i.f.EmbeddedSolrClientFactory - SOLR collection dbv-database-70373bf1-2fdb-4f1d-a2c5-82a5c7595d0f is loaded=
2022-03-14 12:34:37,853 [http-nio-auto-1-exec-5] INFO  c.d.c.s.index.schema.SchemaBuilder - Updating dbv-database-70373bf1-2fdb-4f1d-a2c5-82a5c7595d0f collection schema with 3 fields, 2 dynamic fields and 1 copy fields
2022-03-14 12:34:39,265 [http-nio-auto-1-exec-5] ERROR c.d.m.s.i.c.SIARD2ContentImportStrategy - Failed to open lob at content/schema0/table2/lob4/record0.txt
com.databasepreservation.model.exception.ModuleException: File "./schema0/table2/./content/schema0/table2/lob4/record0.txt" is missing in container
	at com.databasepreservation.modules.siard.in.read.ZipReadStrategy.createInputStream(ZipReadStrategy.java:46)
	at com.databasepreservation.modules.siard.in.read.ZipAndFolderReadStrategy.createInputStream(ZipAndFolderReadStrategy.java:44)
	at com.databasepreservation.modules.siard.in.content.SIARD2ContentImportStrategy.startElement(SIARD2ContentImportStrategy.java:324)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.databasepreservation.modules.siard.in.content.SIARD2ContentImportStrategy.importContent(SIARD2ContentImportStrategy.java:184)
	at com.databasepreservation.modules.siard.in.input.SIARDImportDefault.migrateDatabaseTo(SIARDImportDefault.java:64)
	at com.databasepreservation.DatabaseMigration.migrate(DatabaseMigration.java:123)
	at com.databasepreservation.common.server.controller.SIARDController.convertSIARDtoSolr(SIARDController.java:706)
	at com.databasepreservation.common.server.controller.SIARDController.loadFromLocal(SIARDController.java:669)
	at com.databasepreservation.common.api.v1.CollectionResource.createCollection(CollectionResource.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
	at org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:385)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:560)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:501)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:438)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2022-03-14 12:34:39,267 [http-nio-auto-1-exec-5] ERROR c.d.m.s.i.c.SIARD2ContentImportStrategy - Failed to open lob at content/schema0/table2/lob5/record0.txt
com.databasepreservation.model.exception.ModuleException: File "./schema0/table2/./content/schema0/table2/lob5/record0.txt" is missing in container
	at com.databasepreservation.modules.siard.in.read.ZipReadStrategy.createInputStream(ZipReadStrategy.java:46)
	at com.databasepreservation.modules.siard.in.read.ZipAndFolderReadStrategy.createInputStream(ZipAndFolderReadStrategy.java:44)
	at com.databasepreservation.modules.siard.in.content.SIARD2ContentImportStrategy.startElement(SIARD2ContentImportStrategy.java:324)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.databasepreservation.modules.siard.in.content.SIARD2ContentImportStrategy.importContent(SIARD2ContentImportStrategy.java:184)
	at com.databasepreservation.modules.siard.in.input.SIARDImportDefault.migrateDatabaseTo(SIARDImportDefault.java:64)
	at com.databasepreservation.DatabaseMigration.migrate(DatabaseMigration.java:123)
	at com.databasepreservation.common.server.controller.SIARDController.convertSIARDtoSolr(SIARDController.java:706)
	at com.databasepreservation.common.server.controller.SIARDController.loadFromLocal(SIARDController.java:669)
	at com.databasepreservation.common.api.v1.CollectionResource.createCollection(CollectionResource.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
	at org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:385)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:560)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:501)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:438)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by luis100** [comment]
Could you inspect the SIARD file (change its file extension to .zip and open) and see if the file schema0/table2/./content/schema0/table2/lob4/record0.txt is there?

**Comment by oschihin** [comment]
@luis100 
I'm still stuck with this problem. Is there anything you see from the logs?
Thanks for an update.

**Comment by luis100** [comment]
Hi @oschihin that is nothing we can straitforward identify as a bug or as a misusage (e.g. a corrupt or malformed SIARD file).
For this case, we would need to have access to an example where we could reproduce the issue an analyse the code flow to identify the cause.
